# Generated by Django 5.1.7 on 2025-03-22 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('A', 'A-Shift (6:00 AM - 2:00 PM)'), ('B', 'B-Shift (2:00 PM - 10:00 PM)'), ('C', 'C-Shift (10:00 PM - 6:00 AM)')], max_length=1)),
                ('area', models.CharField(choices=[('Area-1', 'Area-1'), ('Area-2', 'Area-2'), ('Area-3', 'Area-3 (Common Area)')], max_length=20)),
                ('operation_type', models.CharField(choices=[('Feeding', 'Feeding'), ('Stacking', 'Stacking'), ('Reclaiming', 'Reclaiming'), ('Receiving', 'Receiving'), ('Crushing', 'Crushing')], max_length=20)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrushingOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.operation')),
                ('details', models.TextField()),
            ],
            bases=('dashboard.operation',),
        ),
        migrations.AddField(
            model_name='operation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.material'),
        ),
        migrations.CreateModel(
            name='FeedingOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.operation')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
            bases=('dashboard.operation',),
        ),
        migrations.CreateModel(
            name='ReceivingOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.operation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
            bases=('dashboard.operation',),
        ),
        migrations.CreateModel(
            name='ReclaimingOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.operation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
            bases=('dashboard.operation',),
        ),
        migrations.CreateModel(
            name='StackingOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.operation')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.destination')),
            ],
            bases=('dashboard.operation',),
        ),
    ]
