# Generated by Django 5.1.7 on 2025-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_operation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
