# Generated by Django 5.1.7 on 2025-03-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rake_remove_crushingoperation_details_and_more'),
        ('dashboard', 'rename_tonnage_to_quantity'),
    ]

    operations = [
    ]
